spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: main
        git:
          uri: https://github.com/kadirulge/config-server-turkcell
server:
  port: 8888
