spring:
    datasource:
        password: 1234
        url: jdbc:postgresql://localhost:5432/inventorydb-turkcell
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
            javax:
                persistence:
                    validation:
                        mode: none
